name: Deployment Simulation

on:
  workflow_dispatch:   # run manually from GitHub Actions tab

jobs:
  simulate_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build

      - name: Run Docker Containers
        run: docker compose up -d

      - name: Show Running Containers
        run: docker ps -a